version: '3'

services:
  app:
    image: node:18
    ports:
      - 4321:4321
    working_dir: /app
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm dev -- --host 0.0.0.0"
    volumes:
      - ./:/app
